"""
OpenClaw Gateway Client.

Acts as the HTTP bridge between our app and the isolated OpenClaw container.
Handles session management, message sending, and parsing the structured JSON
responses generated by our custom SKILL.md files.
"""
import logging
import json
import httpx
from typing import Optional
from dataclasses import dataclass

from src.core.config import config
from src.core.telemetry import service_executions_total, service_duration_seconds

logger = logging.getLogger(__name__)


@dataclass
class AgentResponse:
    """The structured response parsed from OpenClaw."""
    raw_text: str
    skill: str
    summary: str
    product_data: Optional[dict] = None
    variant_data: Optional[dict] = None
    listings_data: Optional[list] = None
    error: Optional[str] = None


class OpenClawClient:
    """Async HTTP client for OpenClaw Gateway."""

    def __init__(self, base_url: str, token: str):
        self._base_url = base_url.rstrip("/")
        self._token = token

    @property
    def _headers(self) -> dict:
        return {
            "Authorization": f"Bearer {self._token}",
            "Content-Type": "application/json",
        }

    async def send_message(self, session_id: str, text: str) -> AgentResponse:
        """
        Send a message to a specific agent session.
        
        The OpenClaw gateway endpoint expects POST /v1/chat/completions
        with the session key specified in the x-openclaw-session-key header.
        """
        url = f"{self._base_url}/v1/chat/completions"
        payload = {
            "messages": [
                {"role": "user", "content": text}
            ]
        }
        
        headers = self._headers.copy()
        headers["x-openclaw-session-key"] = session_id

        try:
            async with httpx.AsyncClient() as client:
                resp = await client.post(
                    url, json=payload, headers=headers, timeout=60.0
                )
                resp.raise_for_status()
                data = resp.json()
        except httpx.HTTPError as e:
            logger.exception("Failed to communicate with OpenClaw Gateway")
            return AgentResponse(
                raw_text="",
                skill="unknown",
                summary="Sorry, I am having trouble reaching my processing core right now.",
                error=str(e),
            )

        try:
            response_text = data["choices"][0]["message"]["content"]
        except (KeyError, IndexError, TypeError) as e:
            logger.error("Failed to extract content from OpenClaw response: %s", data)
            return AgentResponse(
                raw_text="",
                skill="unknown",
                summary="Sorry, I received an invalid response format from my processing core.",
                error=str(e),
            )

        return self._parse_json_response(response_text)

    def _parse_json_response(self, text: str) -> AgentResponse:
        """Extract and parse the JSON block from the agent's response."""
        # Find the JSON block. Sometimes LLMs wrap it in ```json ... ```
        json_str = text
        if "```json" in text:
            start = text.find("```json") + 7
            end = text.find("```", start)
            if end != -1:
                json_str = text[start:end].strip()
        elif "```" in text:
             start = text.find("```") + 3
             end = text.find("```", start)
             if end != -1:
                 json_str = text[start:end].strip()

        try:
            parsed = json.loads(json_str)
            return AgentResponse(
                raw_text=text,
                skill=parsed.get("skill", "unknown"),
                summary=parsed.get("summary", "Done."),
                product_data=parsed.get("product"),
                variant_data=parsed.get("variant"),
                listings_data=parsed.get("listings"),
                error=parsed.get("error"),
            )
        except json.JSONDecodeError:
            logger.warning("Failed to parse JSON from agent response. Raw text: %s", text)
            # Fallback if the agent just replied with text instead of our requested JSON
            return AgentResponse(
                raw_text=text,
                skill="unknown",
                summary=text, 
            )

    async def health_check(self) -> bool:
        """Check if the gateway is up."""
        url = f"{self._base_url}/"
        try:
            async with httpx.AsyncClient() as client:
                resp = await client.get(url, timeout=5.0)
                return resp.status_code == 200
        except httpx.HTTPError:
            return False


# Singleton instance
agent_client = OpenClawClient(
    base_url=config.OPENCLAW_URL,
    token=config.OPENCLAW_TOKEN,
)
