"""
Custom Prometheus metrics for business-level telemetry.

Complements the auto-instrumented HTTP metrics from
prometheus-fastapi-instrumentator with domain-specific counters.
"""
from prometheus_client import Counter, Histogram, Gauge

# --- Channel Metrics ---
messages_received_total = Counter(
    "messages_received_total",
    "Total inbound messages by channel",
    ["channel"],
)

messages_sent_total = Counter(
    "messages_sent_total",
    "Total outbound messages by channel",
    ["channel"],
)

# --- Service / Intent Metrics ---
intents_classified_total = Counter(
    "intents_classified_total",
    "Total intents classified by the orchestrator",
    ["intent"],
)

service_executions_total = Counter(
    "service_executions_total",
    "Total service executions by service name and outcome",
    ["service", "status"],
)

service_duration_seconds = Histogram(
    "service_duration_seconds",
    "Wall-clock time spent executing a service",
    ["service"],
)

# --- Tracking Metrics ---
active_tracking_jobs_gauge = Gauge(
    "active_tracking_jobs",
    "Current number of active tracking jobs",
)

# --- Report Metrics ---
reports_generated_total = Counter(
    "reports_generated_total",
    "Total reports generated by type",
    ["report_type"],
)
